language: java

jdk: openjdk21

# use containers
sudo: false
dist: trusty

cache:
  directories:
    - $HOME/.m2

env:
  global:
    - MAVEN_OPTS="-server -Xmx512m -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=384m -XX:+UseG1GC -XX:+UseStringDeduplication -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -XX:SoftRefLRUPolicyMSPerMB=50 -Djava.awt.headless=true"

before_script:
  - chmod +x ./mvnw

script:
  - ./mvnw dependency:go-offline # Retrieve All Dependencies
  - ./mvnw clean package -B -e # Build Artifacts
  - ./mvnw verify # Run tests
