language: java
jdk:
  - oraclejdk8

before_install:
  # Install InfluxDB v1.2.1-c1.2.2 (required for integration tests).
  - wget https://dl.influxdata.com/enterprise/releases/influxdb-data_1.2.1-c1.2.2_amd64.deb
  - sudo dpkg -i influxdb-data_1.2.1-c1.2.2_amd64.deb
  # Start InfluxDB and create admin user.
  - sudo service influxdb start
  # Sleep for 5 seconds while InfluxDB starts.
  - sleep 5
  - /usr/bin/influx -execute "CREATE USER root WITH PASSWORD 'root' WITH ALL PRIVILEGES"
  # Enable the http.auth-enabled setting in the InfluxDB config and restart the InfluxDB service.
  - sudo sed -i 's/auth-enabled.*/auth-enabled = true/' /etc/influxdb/influxdb.conf
  - sudo service influxdb restart

script: mvn clean package verify
